# Generated by Django 5.0.4 on 2025-11-14 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_customer_changes"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_transactions",
                        to="api.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Billing Transactions",
                "ordering": ["-transaction_date"],
            },
        ),
    ]
